spring:
  application:
    name: tripweather

server:
  port: 9095

weather:
  api:
    current: https://api.openweathermap.org/data/2.5/weather
    forecast: https://api.openweathermap.org/data/2.5/forecast
    key: ${WEATHER_API_KEY}

    spring:
      security:
        oauth2:
          client:
            registration:
              google:
                client-id: ${GOOGLE_CLIENT_ID}
                client-secret: ${GOOGLE_CLIENT_SECRET}
                scope:
                  - openid
                  - profile
                  - email
            provider:
              google:
                authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
                token-uri: https://oauth2.googleapis.com/token
                jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs