spring:
  application:
    name: tripweather
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9091/.well-known/jwks.json

server:
  port: 9095

weather:
  api:
    current: https://api.openweathermap.org/data/2.5/weather
    forecast: https://api.openweathermap.org/data/2.5/forecast
    key: ${WEATHER_API_KEY}

