spring:
  application:
    name: tripweather

server:
  port: 9095

weather:
  api:
    current: https://api.openweathermap.org/data/2.5/weather
    forecast: https://api.openweathermap.org/data/2.5/forecast
    key: ${WEATHER_API_KEY}